server:
  port: 9001
spring:
  application:
    name: cloud-feign-order9001

# 注册中心配置
eureka:
  client:
    #表示是否将自己注册进EurekaServer,默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
#      defaultZone: http://localhost:7001/eureka
      #集群版
       defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    #避免显示主机名
    instance-id: cloud-feign-order9001
    #显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认为90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 90

#设置feign客户端超时时间
feign:
  client:
    config:
      default:
        #指的是建立连接后从服务器读取到可用资源所用的时间
        connectTimeout: 5000
        #指的是建立连接所用的时间，适用于网络状况iE常的情况下两端连接所用的时间
        readTimeout: 5000
  hystrix:
    enabled: true  # Feign将使用断路器包装所有方法
# 开启日志
logging:
  level:
    com.wxw.cloud.service.PaymentFeignService: debug