
server:
  port: 9527
spring:
  application:
    name: cloud-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #开启动态路由
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
            #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #开启动态路由
          predicates:
           - Path=/api/payment/lb/**   #断言,路径相匹配的进行路由
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    #避免显示主机名
    instance-id: cloud-gateway-service
    #显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认为90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 90

