server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order

eureka:
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
  #避免显示主机名
   instance-id: cloud-hystrix-order80
  #显示IP地址
   prefer-ip-address: true
  #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
   lease-renewal-interval-in-seconds: 30
  #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认为90秒），超时将剔除服务
   lease-expiration-duration-in-seconds: 90

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。


