server:
  port: 8803
spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  cloud:
    stream:
      binders: # 在此配置要绑定的RabbitMQ的配资信息
        defaultRabbit:  #表示定义名称，用于绑定整合
          type: rabbit # 消息组件类型
          environment: #设置rabbitmq相关的环境
            spring:
              rabbitmq:
                host: wxw.plus
                port: 5672
                username: wxw
                password: wxw
                virtual-host: /wxw
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: wxwA    # 配置相同分组 解决消息重复消费问题 ，分组后也支持 持久化功能

management:
  health:
    rabbit:
      enabled: false
#eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer,默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://localhost:7001/eureka
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #避免显示主机名
    instance-id:  cloud-stream-rabbitmq-consumer8803
    #显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认为90秒），超时将剔除服务

